### ISSUE TITLE
Remove prebuilt binaries

### ISSUE THREAD

**Issue by mimi89999** [nowsecure/android-vts#103] opened 2015-12-30 12:00 UTC
Remove prebuilt binaries from the app or replace them by source code.
Related to: #38

**Comment by Fuzion24** [comment] 2015-12-30 19:41
The sourcecode for the prebuilt binaries are in the repo.  This is a dupe of #32

**Closed by Fuzion24** 2015-12-30 19:41 UTC

**Comment by tuxayo** [comment] 2016-01-09 17:34
Is there a way to make the build ignore the prebuilt binaries and build them from source?

It seems that their use is preventing VTS to be accepted on F-Droid

https://gitlab.com/fdroid/fdroiddata/issues/374#note_3071841
